server:
  port: 8000

spring:
  application:
    name: my-zuul-service

zuul:
  routes:
    first-service:
      path: /first-service/**
      url: http://localhost:8081 #http://localhost:8000/first-service/welcome
    second-service:
      path: /second-service/**
      url: http://localhost:8082 #http://localhost:8000/second-service/welcome

