variable "ourdomain" {}
variable "route53zoneid" {}
variable "project_env" {}
variable "mquser" {}
variable "mqpw" {}
variable "node_instance" {}
variable "dbuser" {}
variable "dbpw" {}
variable "ovpnpw" {}
variable "ovpnuser" {}
variable "keypair" {}
